name: tcm
description: TCM 手机客户端.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: 3.27.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  provider: ^6.1.2
  shared_preferences: ^2.5.1
  dio: ^5.8.0+1
  fluttertoast: ^8.2.11
  flutter_smart_dialog: ^4.9.8+5
  cached_network_image: ^3.4.1
  flutter_ytnavigator: ^0.0.3
  flutter_ytlog: ^0.0.2
  flutter_spinkit: ^5.2.1
  flutter_bloc: ^9.0.0
  image_picker: ^1.0.7
  flutter_slidable: ^4.0.0
  pinyin: ^3.3.0
  hugeicons: ^0.0.7
  photo_view: ^0.15.0
  package_info_plus: ^8.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.8
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
